// ============================================================
// DUMMY DATA — SprintFlow
// Realistic mock data for all features
// ============================================================

export const CURRENT_USER = {
  id: 'user-1',
  name: 'Alex Morgan',
  email: 'alex.morgan@sprintflow.io',
  avatar: null,
  initials: 'AM',
  role: 'Product Manager',
  department: 'Engineering',
  location: 'San Francisco, CA',
  timezone: 'America/Los_Angeles',
  joinedAt: '2023-06-15',
  bio: 'Building products that people love. PM by day, designer by night.',
};

export const MEMBERS = [
  { id: 'user-1', name: 'Alex Morgan', email: 'alex@sprintflow.io', avatar: null, initials: 'AM', role: 'Product Manager', color: '#2563EB' },
  { id: 'user-2', name: 'Sarah Chen', email: 'sarah@sprintflow.io', avatar: null, initials: 'SC', role: 'Frontend Engineer', color: '#7C3AED' },
  { id: 'user-3', name: 'Marcus Lee', email: 'marcus@sprintflow.io', avatar: null, initials: 'ML', role: 'Backend Engineer', color: '#059669' },
  { id: 'user-4', name: 'Priya Sharma', email: 'priya@sprintflow.io', avatar: null, initials: 'PS', role: 'UX Designer', color: '#D97706' },
  { id: 'user-5', name: 'Jordan Kim', email: 'jordan@sprintflow.io', avatar: null, initials: 'JK', role: 'DevOps Engineer', color: '#DC2626' },
  { id: 'user-6', name: 'Riley Adams', email: 'riley@sprintflow.io', avatar: null, initials: 'RA', role: 'QA Engineer', color: '#0891B2' },
];

export const WORKSPACES = [
  {
    id: 'ws-1',
    name: 'Engineering Hub',
    description: 'Central workspace for all engineering teams and technical projects.',
    icon: '🚀',
    color: '#2563EB',
    members: ['user-1', 'user-2', 'user-3', 'user-5'],
    projectCount: 8,
    createdAt: '2024-01-10',
    isOwner: true,
    plan: 'Pro',
  },
  {
    id: 'ws-2',
    name: 'Product & Design',
    description: 'Design systems, user research, and product planning workspace.',
    icon: '🎨',
    color: '#7C3AED',
    members: ['user-1', 'user-4'],
    projectCount: 5,
    createdAt: '2024-02-20',
    isOwner: false,
    plan: 'Business',
  },
  {
    id: 'ws-3',
    name: 'Marketing Operations',
    description: 'Campaigns, content creation, and growth initiatives.',
    icon: '📊',
    color: '#059669',
    members: ['user-1', 'user-6'],
    projectCount: 3,
    createdAt: '2024-03-05',
    isOwner: false,
    plan: 'Starter',
  },
];

export const PROJECTS = [
  {
    id: 'proj-1',
    workspaceId: 'ws-1',
    name: 'SprintFlow v2.0',
    description: 'Major redesign and feature overhaul of the core platform.',
    status: 'active',
    priority: 'high',
    startDate: '2024-04-01',
    dueDate: '2024-07-30',
    progress: 68,
    color: '#2563EB',
    icon: '⚡',
    members: ['user-1', 'user-2', 'user-3'],
    taskCount: 47,
    completedTasks: 32,
    tags: ['Frontend', 'Backend', 'Design'],
  },
  {
    id: 'proj-2',
    workspaceId: 'ws-1',
    name: 'API Gateway Migration',
    description: 'Migrate legacy REST API to GraphQL with improved performance.',
    status: 'in_progress',
    priority: 'urgent',
    startDate: '2024-05-15',
    dueDate: '2024-08-15',
    progress: 35,
    color: '#7C3AED',
    icon: '🔧',
    members: ['user-3', 'user-5'],
    taskCount: 28,
    completedTasks: 10,
    tags: ['Backend', 'Infrastructure'],
  },
  {
    id: 'proj-3',
    workspaceId: 'ws-2',
    name: 'Design System 3.0',
    description: 'Build a comprehensive, accessible design system for all products.',
    status: 'active',
    priority: 'medium',
    startDate: '2024-03-01',
    dueDate: '2024-09-30',
    progress: 52,
    color: '#F59E0B',
    icon: '🎨',
    members: ['user-2', 'user-4'],
    taskCount: 34,
    completedTasks: 18,
    tags: ['Design', 'Components'],
  },
  {
    id: 'proj-4',
    workspaceId: 'ws-1',
    name: 'Mobile App (iOS/Android)',
    description: 'Native mobile app for SprintFlow using React Native.',
    status: 'active',
    priority: 'high',
    startDate: '2024-06-01',
    dueDate: '2024-12-01',
    progress: 18,
    color: '#059669',
    icon: '📱',
    members: ['user-1', 'user-2', 'user-4'],
    taskCount: 62,
    completedTasks: 11,
    tags: ['Mobile', 'React Native'],
  },
  {
    id: 'proj-5',
    workspaceId: 'ws-3',
    name: 'Q3 Marketing Campaign',
    description: 'Multi-channel marketing campaign for product launch.',
    status: 'on_hold',
    priority: 'medium',
    startDate: '2024-07-01',
    dueDate: '2024-09-30',
    progress: 12,
    color: '#DC2626',
    icon: '📢',
    members: ['user-1', 'user-6'],
    taskCount: 18,
    completedTasks: 2,
    tags: ['Marketing', 'Content'],
  },
  {
    id: 'proj-6',
    workspaceId: 'ws-1',
    name: 'Security Audit 2024',
    description: 'Comprehensive security review and penetration testing.',
    status: 'completed',
    priority: 'urgent',
    startDate: '2024-02-01',
    dueDate: '2024-04-30',
    progress: 100,
    color: '#0891B2',
    icon: '🔒',
    members: ['user-3', 'user-5'],
    taskCount: 23,
    completedTasks: 23,
    tags: ['Security', 'DevOps'],
  },
];

export const TASKS = [
  // Project proj-1 tasks
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Redesign dashboard with new component library',
    description: 'Implement the new dashboard design using our updated component library. This includes the stats cards, recent activity section, and all chart widgets. Ensure responsiveness across all breakpoints.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'user-2',
    reporterId: 'user-1',
    labels: ['Frontend', 'Design'],
    dueDate: '2024-07-15',
    createdAt: '2024-06-01',
    updatedAt: '2024-07-10',
    commentCount: 8,
    attachmentCount: 3,
    subtasks: [
      { id: 'sub-1', title: 'Design mockups', done: true },
      { id: 'sub-2', title: 'Component implementation', done: true },
      { id: 'sub-3', title: 'Responsive testing', done: false },
      { id: 'sub-4', title: 'Accessibility review', done: false },
    ],
    estimatedHours: 24,
    loggedHours: 18,
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Implement real-time collaboration features',
    description: 'Add WebSocket-based real-time updates for collaborative task editing. Multiple users should be able to see live changes without refreshing the page.',
    status: 'todo',
    priority: 'urgent',
    assigneeId: 'user-3',
    reporterId: 'user-1',
    labels: ['Backend', 'WebSocket'],
    dueDate: '2024-07-20',
    createdAt: '2024-06-10',
    updatedAt: '2024-07-08',
    commentCount: 12,
    attachmentCount: 1,
    subtasks: [
      { id: 'sub-5', title: 'WebSocket server setup', done: false },
      { id: 'sub-6', title: 'Client integration', done: false },
      { id: 'sub-7', title: 'Conflict resolution', done: false },
    ],
    estimatedHours: 40,
    loggedHours: 0,
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Set up CI/CD pipeline with GitHub Actions',
    description: 'Configure automated testing, linting, and deployment pipeline using GitHub Actions. Include staging and production environments.',
    status: 'done',
    priority: 'high',
    assigneeId: 'user-5',
    reporterId: 'user-3',
    labels: ['DevOps', 'Infrastructure'],
    dueDate: '2024-07-01',
    createdAt: '2024-05-20',
    updatedAt: '2024-07-02',
    commentCount: 5,
    attachmentCount: 2,
    subtasks: [],
    estimatedHours: 16,
    loggedHours: 14,
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'User authentication with OAuth2',
    description: 'Implement OAuth2 authentication supporting Google, GitHub, and Microsoft SSO providers.',
    status: 'review',
    priority: 'high',
    assigneeId: 'user-1',
    reporterId: 'user-1',
    labels: ['Auth', 'Security'],
    dueDate: '2024-07-12',
    createdAt: '2024-06-15',
    updatedAt: '2024-07-11',
    commentCount: 3,
    attachmentCount: 0,
    subtasks: [
      { id: 'sub-8', title: 'Google OAuth setup', done: true },
      { id: 'sub-9', title: 'GitHub OAuth setup', done: true },
      { id: 'sub-10', title: 'Microsoft SSO', done: true },
    ],
    estimatedHours: 20,
    loggedHours: 19,
  },
  {
    id: 'task-5',
    projectId: 'proj-1',
    title: 'Build notification system',
    description: 'Create a comprehensive notification system with email, push, and in-app notifications. Include user preferences for notification types.',
    status: 'todo',
    priority: 'medium',
    assigneeId: 'user-2',
    reporterId: 'user-1',
    labels: ['Feature', 'Backend'],
    dueDate: '2024-08-05',
    createdAt: '2024-07-01',
    updatedAt: '2024-07-09',
    commentCount: 2,
    attachmentCount: 1,
    subtasks: [],
    estimatedHours: 32,
    loggedHours: 0,
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    title: 'GraphQL schema design',
    description: 'Design the complete GraphQL schema including all types, queries, and mutations needed for the migration.',
    status: 'done',
    priority: 'urgent',
    assigneeId: 'user-3',
    reporterId: 'user-3',
    labels: ['Architecture', 'GraphQL'],
    dueDate: '2024-06-15',
    createdAt: '2024-05-20',
    updatedAt: '2024-06-16',
    commentCount: 15,
    attachmentCount: 4,
    subtasks: [],
    estimatedHours: 24,
    loggedHours: 26,
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    title: 'Migrate user endpoints to GraphQL',
    description: 'Convert all user-related REST endpoints to GraphQL resolvers.',
    status: 'in_progress',
    priority: 'high',
    assigneeId: 'user-3',
    reporterId: 'user-3',
    labels: ['Backend', 'Migration'],
    dueDate: '2024-07-25',
    createdAt: '2024-06-20',
    updatedAt: '2024-07-10',
    commentCount: 7,
    attachmentCount: 0,
    subtasks: [
      { id: 'sub-11', title: 'GET /users endpoint', done: true },
      { id: 'sub-12', title: 'POST /users endpoint', done: true },
      { id: 'sub-13', title: 'DELETE /users endpoint', done: false },
    ],
    estimatedHours: 16,
    loggedHours: 11,
  },
  {
    id: 'task-8',
    projectId: 'proj-1',
    title: 'Performance optimization & code splitting',
    description: 'Analyze and optimize bundle size, implement lazy loading, and code splitting for better initial load performance.',
    status: 'review',
    priority: 'medium',
    assigneeId: 'user-2',
    reporterId: 'user-1',
    labels: ['Performance', 'Frontend'],
    dueDate: '2024-07-18',
    createdAt: '2024-07-01',
    updatedAt: '2024-07-13',
    commentCount: 4,
    attachmentCount: 2,
    subtasks: [],
    estimatedHours: 12,
    loggedHours: 10,
  },
];

export const COMMENTS = [
  {
    id: 'comment-1',
    taskId: 'task-1',
    authorId: 'user-1',
    content: 'The mockups look great! Just a few tweaks needed on the mobile view. Can we increase the card spacing on mobile?',
    createdAt: '2024-07-10T09:30:00Z',
    reactions: [{ emoji: '👍', count: 3 }, { emoji: '🔥', count: 1 }],
  },
  {
    id: 'comment-2',
    taskId: 'task-1',
    authorId: 'user-2',
    content: 'Updated the mobile spacing. Also added a condensed view for smaller screens. LGTM on the desktop version!',
    createdAt: '2024-07-10T11:15:00Z',
    reactions: [{ emoji: '✅', count: 2 }],
  },
  {
    id: 'comment-3',
    taskId: 'task-1',
    authorId: 'user-4',
    content: 'Could we also add dark mode support here? Would be great to have it consistent with the rest of the app.',
    createdAt: '2024-07-11T14:00:00Z',
    reactions: [],
  },
];

export const NOTIFICATIONS = [
  {
    id: 'notif-1',
    type: 'mention',
    title: 'Alex Morgan mentioned you',
    description: 'in task "Redesign dashboard with new component library"',
    isRead: false,
    createdAt: '2024-07-13T10:30:00Z',
    link: '/tasks/task-1',
    avatar: 'AM',
    avatarColor: '#2563EB',
  },
  {
    id: 'notif-2',
    type: 'assignment',
    title: 'Task assigned to you',
    description: '"Build notification system" has been assigned to you by Alex Morgan',
    isRead: false,
    createdAt: '2024-07-13T09:15:00Z',
    link: '/tasks/task-5',
    avatar: 'AM',
    avatarColor: '#2563EB',
  },
  {
    id: 'notif-3',
    type: 'comment',
    title: 'New comment on your task',
    description: 'Priya Sharma commented on "Redesign dashboard"',
    isRead: false,
    createdAt: '2024-07-12T16:45:00Z',
    link: '/tasks/task-1',
    avatar: 'PS',
    avatarColor: '#D97706',
  },
  {
    id: 'notif-4',
    type: 'status_change',
    title: 'Task status updated',
    description: '"Set up CI/CD pipeline" was moved to Done by Jordan Kim',
    isRead: true,
    createdAt: '2024-07-12T11:20:00Z',
    link: '/tasks/task-3',
    avatar: 'JK',
    avatarColor: '#DC2626',
  },
  {
    id: 'notif-5',
    type: 'due_date',
    title: 'Task due soon',
    description: '"User authentication with OAuth2" is due tomorrow',
    isRead: true,
    createdAt: '2024-07-11T08:00:00Z',
    link: '/tasks/task-4',
    avatar: '⏰',
    avatarColor: '#F59E0B',
    isSystemNotif: true,
  },
  {
    id: 'notif-6',
    type: 'project',
    title: 'Added to project',
    description: 'You\'ve been added to "Mobile App (iOS/Android)" by Alex Morgan',
    isRead: true,
    createdAt: '2024-07-10T13:30:00Z',
    link: '/projects/proj-4',
    avatar: 'AM',
    avatarColor: '#2563EB',
  },
  {
    id: 'notif-7',
    type: 'mention',
    title: 'Marcus Lee mentioned you',
    description: 'in task "GraphQL schema design" — @you check the schema doc',
    isRead: true,
    createdAt: '2024-07-09T17:00:00Z',
    link: '/tasks/task-6',
    avatar: 'ML',
    avatarColor: '#059669',
  },
];

export const ACTIVITY = [
  {
    id: 'act-1',
    userId: 'user-2',
    action: 'moved',
    target: '"Redesign dashboard"',
    targetType: 'task',
    from: 'Todo',
    to: 'In Progress',
    createdAt: '2024-07-13T10:20:00Z',
  },
  {
    id: 'act-2',
    userId: 'user-3',
    action: 'completed',
    target: '"GraphQL schema design"',
    targetType: 'task',
    createdAt: '2024-07-12T15:30:00Z',
  },
  {
    id: 'act-3',
    userId: 'user-1',
    action: 'created',
    target: '"Build notification system"',
    targetType: 'task',
    createdAt: '2024-07-12T11:00:00Z',
  },
  {
    id: 'act-4',
    userId: 'user-5',
    action: 'completed',
    target: '"CI/CD pipeline"',
    targetType: 'task',
    createdAt: '2024-07-12T09:45:00Z',
  },
  {
    id: 'act-5',
    userId: 'user-4',
    action: 'commented on',
    target: '"Redesign dashboard"',
    targetType: 'task',
    createdAt: '2024-07-11T16:00:00Z',
  },
  {
    id: 'act-6',
    userId: 'user-2',
    action: 'started',
    target: '"Performance optimization"',
    targetType: 'task',
    createdAt: '2024-07-11T10:00:00Z',
  },
  {
    id: 'act-7',
    userId: 'user-1',
    action: 'created project',
    target: '"Mobile App (iOS/Android)"',
    targetType: 'project',
    createdAt: '2024-07-10T09:00:00Z',
  },
];

export const DASHBOARD_STATS = {
  totalProjects: 6,
  totalTasks: 219,
  completedTasks: 67,
  pendingTasks: 120,
  overdueTasks: 12,
  teamMembers: 6,
  activeWorkspaces: 3,
  thisWeekCompleted: 18,
};

export const CHART_DATA = {
  taskCompletion: [
    { month: 'Feb', completed: 42, created: 55 },
    { month: 'Mar', completed: 58, created: 62 },
    { month: 'Apr', completed: 73, created: 78 },
    { month: 'May', completed: 61, created: 70 },
    { month: 'Jun', completed: 85, created: 88 },
    { month: 'Jul', completed: 67, created: 72 },
  ],
  projectProgress: [
    { name: 'SprintFlow v2.0', progress: 68 },
    { name: 'API Migration', progress: 35 },
    { name: 'Design System', progress: 52 },
    { name: 'Mobile App', progress: 18 },
    { name: 'Marketing', progress: 12 },
  ],
  priorityDistribution: [
    { name: 'Urgent', value: 12, color: '#EF4444' },
    { name: 'High', value: 35, color: '#F97316' },
    { name: 'Medium', value: 48, color: '#F59E0B' },
    { name: 'Low', value: 25, color: '#22C55E' },
  ],
};

export const LABELS = [
  { id: 'label-1', name: 'Frontend', color: '#3B82F6' },
  { id: 'label-2', name: 'Backend', color: '#8B5CF6' },
  { id: 'label-3', name: 'Design', color: '#EC4899' },
  { id: 'label-4', name: 'DevOps', color: '#F59E0B' },
  { id: 'label-5', name: 'Security', color: '#EF4444' },
  { id: 'label-6', name: 'Bug', color: '#DC2626' },
  { id: 'label-7', name: 'Feature', color: '#2563EB' },
  { id: 'label-8', name: 'Performance', color: '#059669' },
  { id: 'label-9', name: 'Infrastructure', color: '#0891B2' },
  { id: 'label-10', name: 'Documentation', color: '#64748B' },
];
